### ISSUE TITLE
Single-Page Web Apps not work

### ISSUE THREAD

**Issue by sumjur** [kennethreitz/responder#247]
responder v1.1.2

**Comment by sumjur** [comment]
I found that this issue has been resolved in 'master' branch, but no new version has been released.

https://github.com/kennethreitz/responder/blob/master/responder/api.py#L436

**Comment by amp180** [comment]
Thanks sumjur. :)

Added this to my Pipfile to use the previous version for now, it might save somebody else some time.

```
responder = "<1.1.2"
starlette = "<0.8.0"
```

**Comment by Serkan-devel** [comment]
Editing the pipfile that way doesn't work

<pre> 
(...)
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable
(...)
</pre>

When will the fix be pushed to pypi?

**Comment by Serkan-devel** [comment]
@amp180 I have responder 1.1.1 installed, using the pipfile, you've provided but I still get the same errors.

My setup is simple placing this [static content](https://git.pleroma.social/pleroma/pleroma-fe/-/jobs/10334/artifacts/download) and unpack it into the /static directory, and I get a blank page. When I navigate to where the favicon.png should be, it still serves the index.html-file.

My setup is the same as on this [other issue](https://github.com/kennethreitz/responder/issues/252) and my app looks like this.

<pre>
$ cat app.py 
import responder
(...)
api = responder.API()

api.add_route("/", static=True)
(...)
if __name__=="__main__":
    api.run()
</pre>

and these are the full logs while running it

<pre>
$ pipenv run python app.py
INFO: Started server process [8213]
INFO: Waiting for application startup.
INFO: Uvicorn running on http://127.0.0.1:5042 (Press CTRL+C to quit)
INFO: ('127.0.0.1', 49310) - "GET / HTTP/1.1" 200
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 389, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable
INFO: ('127.0.0.1', 49310) - "GET /font/css/fontello.css HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 389, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable
INFO: ('127.0.0.1', 49312) - "GET /font/css/animation.css HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 389, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable
INFO: ('127.0.0.1', 49314) - "GET /css/app.0808aeafc6252b3050ea95b17dcaff1a.css HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 389, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable
INFO: ('127.0.0.1', 49316) - "GET /js/manifest.82a6d9e86dea57362289.js HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 389, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable
INFO: ('127.0.0.1', 49318) - "GET /js/vendor.32c621c7157f34c20923.js HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 389, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable
INFO: ('127.0.0.1', 49320) - "GET /js/app.85926c1b8f295e2260b4.js HTTP/1.1" 500
INFO: ('127.0.0.1', 49322) - "GET /favicon.png HTTP/1.1" 200
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 389, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable
INFO: ('127.0.0.1', 49322) - "GET /js/vendor.32c621c7157f34c20923.js HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 389, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/prox-fe-P-yd2Xjk/lib/python3.6/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable
INFO: ('127.0.0.1', 49324) - "GET /js/app.85926c1b8f295e2260b4.js HTTP/1.1" 500
^CINFO: Stopping server process [8213]
INFO: Waiting for application shutdown.
</pre>

**Comment by amp180** [comment]
Hi again Serkan,
What python version are you running the app with? 

Responder requires python 3.7 [in it's Pipfile](https://raw.githubusercontent.com/kennethreitz/responder/master/Pipfile), so it might be pretty hard for you to get it running properly on 3.6. 

I tried to set up using 3.6 because it was listed in your traceback, but I didn't get very far, I got an error about some of the imports responder uses being missing from the stdlib before the app even started.

**Comment by Fak3** [comment]
I have the same error on python 3.7 and responder v 1.2.0:
```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/u1/.virtualenvs/spbelectmap/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/home/u1/.virtualenvs/spbelectmap/lib/python3.7/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/u1/.virtualenvs/spbelectmap/lib/python3.7/site-packages/uvicorn/middleware/debug.py", line 80, in __call__
    await asgi(receive, self.send)
  File "/home/u1/.virtualenvs/spbelectmap/lib/python3.7/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/home/u1/.virtualenvs/spbelectmap/lib/python3.7/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/lib64/python3.7/asyncio/tasks.py", line 388, in wait_for
    return await fut
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/u1/.virtualenvs/spbelectmap/lib/python3.7/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/home/u1/.virtualenvs/spbelectmap/lib/python3.7/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable
```

**Comment by taoufik07** [comment]
Fixed #297
