### ISSUE TITLE
ModuleNotFoundError: No module named 'starlette.lifespan'

### ISSUE THREAD

**Issue by aiia** [kennethreitz/responder#255]
There's no **lifespan** module in the current 0.9.1 version of Starlette already.

**Comment by tomchristie** [comment]
Responder is pinned to Starlette 0.8 series, no?

https://github.com/kennethreitz/responder/blob/master/setup.py#L25

**Comment by aiia** [comment]
I used Kenneth's pipenv for installation - and it delivered the recent Starlette.

**Comment by ranjanprj** [comment]
problem solved by using starlette 0.8 version

`pip install starlette==0.8 
`

**Comment by ibnesayeed** [comment]
> Responder is pinned to Starlette 0.8 series, no?

Yes it is, but this change was made a few days after the last release `v1.1.2`, so the current latest release of `responder` in PyPi has broken dependencies as the `0.9` series of `starlette` (released a couple days ago) now handles `lifespan` as a middleware.

While, releasing a new version of the `responder` should fix this issue for now, but going forward the code should adapt to the change in the `starlette` about the `lifespan` or else we will be left with using an old code of a critical dependency.

**Comment by hktalent** [comment]
in mac os @ranjanprj 
```
pip3 install starlette==0.8
```

**Comment by theolampert** [comment]
@kennethreitz I think this should be reopened since it's still happening on a fresh install, following the readme:
```shell
pipenv install responder --pre
pipenv run python app.py
```

produces the following:
```shell
ModuleNotFoundError: No module named 'starlette.lifespan'
```

**Comment by jvalle3** [comment]
the same for me, same error on a fresh install

**Comment by jasonehines** [comment]
Just installed and I'm also getting this.

**Comment by ibnesayeed** [comment]
These changes are merged, but not released yet. The last release was made on Nov 11, more than a month ago. Can you try installing from the development branch and see if the issue still exists?

```
$ pipenv install -e git+https://github.com/kennethreitz/responder.git#egg=responder
```
